use crate::config;
use crate::features::research::acl::expectation_source_adapter_factory::build_expectation_layer_snapshot_from_config as build_live_expectation_layer_snapshot;
use chrono::NaiveDate;
use serde::{Deserialize, Serialize};

use crate::features::research::domain::expectation::{
    derive_lifecycle_state, ExpectationEventType, ExpectationObservation, ExpectationPressure,
    RevisionDirection, SourceHealth, SurpriseState,
};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) struct ExpectationLayerSnapshot {
    pub as_of_date: NaiveDate,
    pub decision_weight_percent: u8,
    pub trade_signal: bool,
    pub gate_effect: String,
    pub execution_effect: String,
    pub position_sizing_effect: String,
    pub observations: Vec<ExpectationObservation>,
}

/// 期待値観測の first phase fixture を組み立てる。
#[cfg(test)]
#[allow(clippy::too_many_lines)]
pub(crate) fn build_expectation_layer_snapshot() -> ExpectationLayerSnapshot {
    build_expectation_layer_fixture_snapshot()
}

/// 期待値観測の first phase fixture を組み立てる。
#[allow(clippy::too_many_lines)]
pub(crate) fn build_expectation_layer_fixture_snapshot() -> ExpectationLayerSnapshot {
    let as_of_date = NaiveDate::from_ymd_opt(2026, 6, 18).expect("valid expectation fixture date");
    ExpectationLayerSnapshot {
        as_of_date,
        decision_weight_percent: 0,
        trade_signal: false,
        gate_effect: "none".to_string(),
        execution_effect: "none".to_string(),
        position_sizing_effect: "none".to_string(),
        observations: vec![
            observation(
                "TSLA",
                "2026Q2",
                ExpectationEventType::DeliveryConsensus,
                "~401k deliveries",
                "未発表",
                "deliveries",
                "fixture: market-consensus-sample",
                11,
                Some("435k"),
                Some("372k"),
                Some("401k"),
                Some("402k"),
                RevisionDirection::Up,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.82),
                SourceHealth::Succeeded,
                "市場はすでに約40万台前後を基準として見ている。",
                as_of_date,
            ),
            observation(
                "NVDA",
                "2026Q2",
                ExpectationEventType::EarningsConsensus,
                "$1.19 EPS",
                "未発表",
                "earnings_usd_per_share",
                "fixture: market-consensus-sample",
                18,
                Some("$1.31"),
                Some("$1.08"),
                Some("$1.19"),
                Some("$1.20"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Extreme,
                Some(0.90),
                SourceHealth::Succeeded,
                "利益期待は高止まりしており、発表前の織り込みが大きい。",
                as_of_date,
            ),
            observation(
                "NVDA",
                "2026Q2",
                ExpectationEventType::RevenueConsensus,
                "$46.8B revenue",
                "未発表",
                "revenue_usd_billion",
                "fixture: market-consensus-sample",
                18,
                Some("$48.1B"),
                Some("$45.9B"),
                Some("$46.8B"),
                Some("$46.9B"),
                RevisionDirection::Up,
                SurpriseState::NotReleased,
                ExpectationPressure::Extreme,
                Some(0.91),
                SourceHealth::Succeeded,
                "売上期待は AI インフラ需要の継続を前提にしている。",
                as_of_date,
            ),
            observation(
                "NVDA",
                "2026Q2",
                ExpectationEventType::MarginConsensus,
                "71.2% gross margin",
                "未発表",
                "gross_margin_pct",
                "fixture: market-consensus-sample",
                16,
                Some("72.4%"),
                Some("70.1%"),
                Some("71.2%"),
                Some("71.4%"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.84),
                SourceHealth::Succeeded,
                "粗利率は製品ミックスと供給制約の改善期待を織り込んでいる。",
                as_of_date,
            ),
            observation(
                "GOOG",
                "2026Q2",
                ExpectationEventType::CloudGrowthConsensus,
                "+31% y/y cloud growth",
                "未発表",
                "cloud_growth_pct",
                "fixture: market-consensus-sample",
                14,
                Some("+34%"),
                Some("+27%"),
                Some("+31%"),
                Some("+31.5%"),
                RevisionDirection::Up,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.79),
                SourceHealth::Succeeded,
                "Cloud 成長期待は継続的な企業需要を前提にしている。",
                as_of_date,
            ),
            observation(
                "GOOG",
                "2026Q2",
                ExpectationEventType::CapexConsensus,
                "$14.6B capex",
                "未発表",
                "capex_usd_billion",
                "fixture: market-consensus-sample",
                13,
                Some("$15.2B"),
                Some("$13.8B"),
                Some("$14.6B"),
                Some("$14.7B"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Normal,
                Some(0.73),
                SourceHealth::Succeeded,
                "CAPEX はクラウド拡張と AI 基盤投資の持続を示す。",
                as_of_date,
            ),
            observation(
                "GOOG",
                "2026Q2",
                ExpectationEventType::EarningsConsensus,
                "$1.89 EPS",
                "未発表",
                "earnings_usd_per_share",
                "fixture: market-consensus-sample",
                16,
                Some("$2.03"),
                Some("$1.75"),
                Some("$1.89"),
                Some("$1.90"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.80),
                SourceHealth::Succeeded,
                "利益期待は広告とクラウドの両輪を織り込んでいる。",
                as_of_date,
            ),
            observation(
                "MSFT",
                "2026Q2",
                ExpectationEventType::CloudGrowthConsensus,
                "+27% y/y cloud growth",
                "未発表",
                "cloud_growth_pct",
                "fixture: market-consensus-sample",
                15,
                Some("+30%"),
                Some("+24%"),
                Some("+27%"),
                Some("+27.4%"),
                RevisionDirection::Up,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.86),
                SourceHealth::Succeeded,
                "Azure と AI 需要の組み合わせが高い基準を作っている。",
                as_of_date,
            ),
            observation(
                "MSFT",
                "2026Q2",
                ExpectationEventType::ProductEventExpectation,
                "copilot / product event upside",
                "未発表",
                "product_event",
                "fixture: market-consensus-sample",
                10,
                Some("high"),
                Some("normal"),
                Some("high"),
                Some("high"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Normal,
                Some(0.70),
                SourceHealth::Succeeded,
                "製品イベントは数字ではなく期待の微調整として観測される。",
                as_of_date,
            ),
            observation(
                "MSFT",
                "2026Q2",
                ExpectationEventType::CapexConsensus,
                "$15.4B capex",
                "未発表",
                "capex_usd_billion",
                "fixture: market-consensus-sample",
                12,
                Some("$16.1B"),
                Some("$14.7B"),
                Some("$15.4B"),
                Some("$15.5B"),
                RevisionDirection::Up,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.81),
                SourceHealth::Succeeded,
                "CAPEX は AI データセンター投資の継続期待を示している。",
                as_of_date,
            ),
            observation(
                "PLTR",
                "2026Q2",
                ExpectationEventType::RevenueConsensus,
                "$0.95B revenue",
                "未発表",
                "revenue_usd_billion",
                "fixture: market-consensus-sample",
                9,
                Some("$1.02B"),
                Some("$0.88B"),
                Some("$0.95B"),
                Some("$0.96B"),
                RevisionDirection::Up,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.77),
                SourceHealth::Succeeded,
                "売上期待は政府案件と商用拡大の両方を織り込んでいる。",
                as_of_date,
            ),
            observation(
                "PLTR",
                "2026Q2",
                ExpectationEventType::UserGrowthConsensus,
                "+28% user growth",
                "未発表",
                "user_growth_pct",
                "fixture: market-consensus-sample",
                8,
                Some("+32%"),
                Some("+24%"),
                Some("+28%"),
                Some("+28.4%"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::High,
                Some(0.74),
                SourceHealth::Succeeded,
                "利用拡大の期待は継続的な導入速度に依存している。",
                as_of_date,
            ),
            observation(
                "PLTR",
                "2026Q2",
                ExpectationEventType::MarginConsensus,
                "44.0% gross margin",
                "未発表",
                "gross_margin_pct",
                "fixture: market-consensus-sample",
                8,
                Some("45.2%"),
                Some("42.9%"),
                Some("44.0%"),
                Some("44.1%"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Normal,
                Some(0.69),
                SourceHealth::Succeeded,
                "マージン期待は高成長維持と利益率改善の両立を前提にしている。",
                as_of_date,
            ),
            observation(
                "ISRG",
                "2026Q2",
                ExpectationEventType::ProcedureGrowthConsensus,
                "+15% procedure growth",
                "未発表",
                "procedure_growth_pct",
                "fixture: market-consensus-sample",
                7,
                Some("+17%"),
                Some("+13%"),
                Some("+15%"),
                Some("+15.2%"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Normal,
                Some(0.72),
                SourceHealth::Succeeded,
                "施術件数は回復基調を前提とした保守的な織り込みになっている。",
                as_of_date,
            ),
            observation(
                "ISRG",
                "2026Q2",
                ExpectationEventType::RevenueConsensus,
                "$2.02B revenue",
                "未発表",
                "revenue_usd_billion",
                "fixture: market-consensus-sample",
                7,
                Some("$2.08B"),
                Some("$1.96B"),
                Some("$2.02B"),
                Some("$2.03B"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Normal,
                Some(0.71),
                SourceHealth::Succeeded,
                "売上期待は手術回復と設備更新サイクルを反映している。",
                as_of_date,
            ),
            observation(
                "ISRG",
                "2026Q2",
                ExpectationEventType::MarginConsensus,
                "68.4% gross margin",
                "未発表",
                "gross_margin_pct",
                "fixture: market-consensus-sample",
                7,
                Some("69.0%"),
                Some("67.8%"),
                Some("68.4%"),
                Some("68.5%"),
                RevisionDirection::Stable,
                SurpriseState::NotReleased,
                ExpectationPressure::Low,
                Some(0.68),
                SourceHealth::Succeeded,
                "利益率は安定的だが、サプライズは主に需要側で発生しやすい。",
                as_of_date,
            ),
        ],
    }
}

/// 期待値観測の live source snapshot を組み立てる。
pub(crate) fn build_expectation_layer_snapshot_from_config(
    app_config: &config::AppConfig,
) -> ExpectationLayerSnapshot {
    build_live_expectation_layer_snapshot(app_config)
}

#[allow(clippy::too_many_arguments)]
fn observation(
    subject: &str,
    period: &str,
    event_type: ExpectationEventType,
    expected_value: &str,
    actual_value: &str,
    unit: &str,
    consensus_source: &str,
    estimate_count: usize,
    estimate_high: Option<&str>,
    estimate_low: Option<&str>,
    estimate_median: Option<&str>,
    estimate_average: Option<&str>,
    revision_direction: RevisionDirection,
    surprise_state: SurpriseState,
    expectation_pressure: ExpectationPressure,
    confidence: Option<f64>,
    source_health: SourceHealth,
    interpretation: &str,
    date: NaiveDate,
) -> ExpectationObservation {
    let lifecycle_state = derive_lifecycle_state(period, date, actual_value, None, None, None);
    ExpectationObservation {
        subject: subject.to_string(),
        period: period.to_string(),
        as_of_date: date,
        event_type,
        lifecycle_state,
        expected_value: expected_value.to_string(),
        actual_value: actual_value.to_string(),
        result: None,
        surprise_percent: None,
        market_reaction: None,
        released_at: None,
        archived_at: None,
        unit: unit.to_string(),
        consensus_source: consensus_source.to_string(),
        estimate_count,
        estimate_high: estimate_high.map(ToString::to_string),
        estimate_low: estimate_low.map(ToString::to_string),
        estimate_median: estimate_median.map(ToString::to_string),
        estimate_average: estimate_average.map(ToString::to_string),
        revision_direction,
        surprise_state,
        expectation_pressure,
        confidence,
        source_health,
        interpretation: interpretation.to_string(),
        observed_at: date,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn observation_derives_upcoming_for_future_period() {
        let as_of_date = NaiveDate::from_ymd_opt(2026, 6, 18).expect("valid date");
        let observation = observation(
            "TSLA",
            "2026Q3",
            ExpectationEventType::DeliveryConsensus,
            "~405k deliveries",
            "未発表",
            "deliveries",
            "fixture",
            0,
            None,
            None,
            None,
            None,
            RevisionDirection::Unknown,
            SurpriseState::NotReleased,
            ExpectationPressure::Low,
            None,
            SourceHealth::Unavailable,
            "future quarter",
            as_of_date,
        );

        assert_eq!(
            observation.lifecycle_state,
            crate::features::research::domain::expectation::ExpectationLifecycleState::Upcoming
        );
    }

    #[test]
    fn observation_derives_released_and_archived_states_from_dates() {
        let as_of_date = NaiveDate::from_ymd_opt(2026, 6, 18).expect("valid date");
        let released_at = NaiveDate::from_ymd_opt(2026, 6, 19).expect("valid date");
        let archived_at = NaiveDate::from_ymd_opt(2026, 6, 25).expect("valid date");

        let released = crate::features::research::domain::expectation::derive_lifecycle_state(
            "2026Q2",
            as_of_date,
            "392k deliveries",
            None,
            Some(released_at),
            None,
        );
        let compared = crate::features::research::domain::expectation::derive_lifecycle_state(
            "2026Q2",
            as_of_date,
            "392k deliveries",
            Some(crate::features::research::domain::expectation::ExpectationResult::Beat),
            Some(released_at),
            None,
        );
        let archived = crate::features::research::domain::expectation::derive_lifecycle_state(
            "2026Q2",
            as_of_date,
            "392k deliveries",
            Some(crate::features::research::domain::expectation::ExpectationResult::Beat),
            Some(released_at),
            Some(archived_at),
        );

        assert_eq!(
            released,
            crate::features::research::domain::expectation::ExpectationLifecycleState::Released
        );
        assert_eq!(
            compared,
            crate::features::research::domain::expectation::ExpectationLifecycleState::Compared
        );
        assert_eq!(
            archived,
            crate::features::research::domain::expectation::ExpectationLifecycleState::Archived
        );
    }
}
