use crate::config::AppConfig;
use crate::core::decision::DecisionPacket;
use crate::core::asset_state::AssetState;
use crate::core::market_regime::MarketState;
use crate::core::action_matrix::AssetAction;
use anyhow::Result;
use tabled::{settings::Style, Table, Tabled};

#[derive(Tabled)]
pub struct TerminalRow {
    #[tabled(rename = "Symbol")]
    pub symbol: String,
    #[tabled(rename = "State")]
    pub state: String,
    #[tabled(rename = "Action")]
    pub action: String,
    #[tabled(rename = "Dist")]
    pub owner_dev: String,
    #[tabled(rename = "Z-Score")]
    pub strength_z: String,
}

#[derive(Tabled)]
pub struct TerminalRowHeld {
    pub symbol: String,
    pub qty: f64,
    pub avg_price: f64,
    pub current_price: f64,
    pub pl: String,
}

pub struct ReportResult {
    pub markdown_body: String,
    pub archival_markdown: String,
    #[allow(dead_code)]
    pub state_code: String,
}


pub fn generate_refined_report(
    _config: &AppConfig,
    packet: &DecisionPacket,
    realized_pl: f64,
    positions: &std::collections::HashMap<String, (f64, f64)>,
    mode: &crate::core::runtime_mode::ExecutionMode,
    failed_symbols: Vec<String>,
) -> Result<ReportResult> {
    let date_str = packet.date.format("%Y-%m-%d").to_string();

    let telegram_card = format_telegram_card(packet, mode, &failed_symbols, positions);

    let mut rows = Vec::new();
    for asset in &packet.assets {
        let emoji = match asset.state {
            AssetState::OPTIMAL => "🔥",
            AssetState::PULLBACK => "🏹",
            AssetState::OVERHEAT => "🌋",
            AssetState::DEFEND => "🛡️",
            _ => "▫️",
        };

        rows.push(TerminalRow {
            symbol: asset.symbol.clone(),
            state: format!("{} {:?}", emoji, asset.state),
            action: format!("{:?}", asset.action),
            owner_dev: format!("{:+.1}%", asset.deviation.unwrap_or(0.0)),
            strength_z: format!("{:.1}σ", asset.z_score.unwrap_or(0.0)),
        });
    }

    let mut table = Table::new(&rows);
    table.with(Style::modern());

    println!("\n--- 🐕 Stock Sentinel Decision Packet ({}) ---", date_str);
    println!("Headline: {}", packet.telegram.headline);
    println!("Summary:  {}", packet.telegram.summary);
    println!("-----------------------------------------------");
    println!("{}", table);

    let mut _total_equity = 0.0;

    let mut held_rows = Vec::new();
    for (sym, (qty, avg)) in positions {
        if *qty > 0.0 {
            let current_price = packet.assets.iter()
                .find(|a| a.symbol == *sym)
                .map(|a| a.price)
                .unwrap_or(0.0);
                
            let open_pl = (current_price - avg) * qty;
            _total_equity += current_price * qty;

            held_rows.push(TerminalRowHeld {
                symbol: sym.clone(),
                qty: *qty,
                avg_price: *avg,
                current_price,
                pl: format!("{:+.2}", open_pl),
            });
        }
    }


    if !held_rows.is_empty() {
        println!("\n💼 Portfolio Status");
        let mut held_table = Table::new(&held_rows);
        held_table.with(Style::sharp());
        println!("{}", held_table);
        println!(" • Total Realized P/L: {:+.2}", realized_pl);
    }

    // Archival Markdown (Clean formatting for reports/YYYY-MM-DD.md)
    let mut archival_md = format!("# Sentinel Decision Report: {}\n\n", date_str);
    archival_md.push_str(&format!("## 📋 Headline\n> {}\n\n", packet.telegram.headline));
    archival_md.push_str(&format!("## 📝 Summary\n{}\n\n", packet.telegram.summary));
    
    archival_md.push_str("## 📈 Market & Asset Decisions\n\n");
    archival_md.push_str("| Symbol | State | Action | Deviation | Z-Score |\n");
    archival_md.push_str("|---|---|---|---|---|\n");
    for row in &rows {
        archival_md.push_str(&format!("| {} | {} | {} | {} | {} |\n", 
            row.symbol, row.state, row.action, row.owner_dev, row.strength_z));
    }
    archival_md.push_str("\n\n");

    if !held_rows.is_empty() {
        archival_md.push_str("## 💼 Portfolio Status\n\n");
        archival_md.push_str("| Symbol | Qty | Avg Price | Current Price | Open P/L |\n");
        archival_md.push_str("|---|---|---|---|---|\n");
        for h in &held_rows {
            archival_md.push_str(&format!("| {} | {:.2} | {:.2} | {:.2} | {} |\n", 
                h.symbol, h.qty, h.avg_price, h.current_price, h.pl));
        }
        archival_md.push_str(&format!("\n**Total Realized P/L**: {:+.2}\n", realized_pl));
    }

    archival_md.push_str(&format!("\n\n---\n*Generated by Sentinel Engine 2.0 at {}*", chrono::Local::now().to_rfc3339()));

    let state_code = format!("{:?}", packet.market_regime.market_state);

    Ok(ReportResult {
        markdown_body: telegram_card,
        archival_markdown: archival_md,
        state_code,
    })
}

fn format_telegram_card(
    packet: &DecisionPacket, 
    mode: &crate::core::runtime_mode::ExecutionMode,
    failed_symbols: &[String],
    positions: &std::collections::HashMap<String, (f64, f64)>,
) -> String {
    use crate::core::action_matrix::AssetAction;

    let date_str = packet.date.format("%Y-%m-%d").to_string();
    let state = packet.market_regime.market_state;
    let risk = packet.market_regime.risk_overlay;

    // 1. Header & Bias
    let state_str = format!("{:?}", state).to_uppercase();
    // Humanize Risk formatting
    let risk_str = match risk {
        crate::core::market_regime::RiskOverlay::NORMAL => "Risk Normal",
        crate::core::market_regime::RiskOverlay::DEFENSIVE => "Risk Defensive",
        _ => "Risk Mixed",
    };

    let mut card = format!("<b>{} | {}</b>\n", state_str, risk_str);
    card.push_str(&format!("Bias: {}\n", packet.telegram.bias));

    // Defensive Warning First
    if state == MarketState::DEFENSIVE {
        card.push_str("Warning: Circuit Breaker Active\n");
    }

    card.push_str(&format!("{}\n\n", date_str));

    // 2. Policy & Portfolio Section
    let min_exp = (packet.portfolio_policy.target_exposure_min * 100.0) as i32;
    let max_exp = (packet.portfolio_policy.target_exposure_max * 100.0) as i32;
    
    card.push_str(&format!("仓位: {}-{}%\n", min_exp, max_exp));
    card.push_str(&format!("策略: {}\n", packet.telegram.summary));
    
    if !positions.is_empty() {
        card.push_str(&format!("持仓: {} positions\n", positions.len()));
    }
    card.push('\n');

    // 3. Top Actions (v3 Visual Tags & Localization)
    if state == MarketState::DEFENSIVE {
        card.push_str("<b>Priority Actions</b>\n");
    } else {
        card.push_str("<b>Top Actions</b>\n");
    }

    let top_assets = select_top_actions(&packet.assets, state);
    
    for (idx, asset) in top_assets.iter().enumerate() {
        let tag = if asset.action_changed {
            if asset.prev_action.is_none() { " [NEW]" } else { " [CHANGED]" }
        } else {
            ""
        };
        
        let local_action = match asset.action {
            AssetAction::ACCUMULATE => "加仓",
            AssetAction::REDUCE => "减仓",
            AssetAction::FREEZE => "冻结",
            AssetAction::AVOID => "回避",
            AssetAction::HOLD => "持有",
            AssetAction::OBSERVE => "观察",
            AssetAction::WAIT => "等待",
        };

        card.push_str(&format!("{}. {}  {}  {:?}{}\n", idx + 1, asset.symbol, local_action, asset.state, tag));
        let reason = telegram_reason(asset);
        card.push_str(&format!("   {}\n", reason));
    }
    card.push('\n');

    // 4. Signals Section
    if state == MarketState::DEFENSIVE {
        card.push_str("<b>Risk Signals</b>\n");
    } else {
        card.push_str("<b>Signals</b>\n");
    }

    let f = &packet.market_features;
    card.push_str(&format!(
        "Confidence {:.1} ({})\n", 
        f.system_confidence, 
        confidence_label(f.system_confidence)
    ));
    
    card.push_str(&format!(
        "Stability {:.1} ({}) | Age {}d\n", 
        f.stability_score, 
        stability_label(f.stability_score), 
        f.regime_age
    ));

    let flow_str = f.flow_acceleration.map(|x| format!("{:+.2}", x)).unwrap_or_else(|| "N/A".to_string());
    let mode_str = match mode {
        crate::core::runtime_mode::ExecutionMode::Live => "Live",
        crate::core::runtime_mode::ExecutionMode::DryRun => "Dry Run",
        crate::core::runtime_mode::ExecutionMode::Disabled => "Disabled",
    };

    if state == MarketState::DEFENSIVE {
        card.push_str(&format!("Execution {}\n", mode_str));
    } else {
        card.push_str(&format!("Flow {} | Execution {}\n", flow_str, mode_str));
    }

    // 5. Data Warning (Specific Symbols)
    if !failed_symbols.is_empty() {
        let warning_type = match failed_symbols.len() {
            1 => "Notice",
            2..=3 => "Warning",
            _ => "Critical",
        };
        
        let symbols_str = failed_symbols.join(", ");
        card.push_str(&format!("\nData {}: {} fetch failed\n", warning_type, symbols_str));
    }

    card
}

fn confidence_label(val: f64) -> &'static str {
    if val >= 80.0 { "High" } else if val >= 65.0 { "Moderate" } else { "Low" }
}

fn stability_label(val: f64) -> &'static str {
    if val >= 25.0 { "Stable" } else if val >= 15.0 { "Mixed" } else { "Fragile" }
}

fn telegram_reason(asset: &crate::core::action_matrix::AssetActionDecision) -> String {
    if asset.action_changed {
        return match asset.prev_action {
            Some(prev) => format!("由 {:?} -> {:?}，今日信号变化", prev, asset.action),
            None => "今日新进入关注列表".to_string(),
        };
    }

    match asset.state {
        AssetState::PULLBACK => "趋势内回撤，允许补仓".to_string(),
        AssetState::OPTIMAL => "结构最强，适合持有".to_string(),
        AssetState::DEFEND => "结构转弱，避免参与".to_string(),
        AssetState::OVERHEAT => "偏离过热，避免追高".to_string(),
        AssetState::CRUISE => "趋势延续，持有为主".to_string(),
        AssetState::CAUTION => "信号转弱，暂不加仓".to_string(),
        AssetState::FORMING => "结构未完成，继续观察".to_string(),
    }
}

fn select_top_actions(
    assets: &[crate::core::action_matrix::AssetActionDecision],
    state: MarketState,
) -> Vec<crate::core::action_matrix::AssetActionDecision> {
    let mut items = assets.to_vec();

    fn action_prio(a: AssetAction) -> i32 {
        match a {
            AssetAction::ACCUMULATE => 100,
            AssetAction::REDUCE => 90,
            AssetAction::FREEZE => 80,
            AssetAction::AVOID => 70,
            AssetAction::HOLD => 60,
            AssetAction::OBSERVE => 50,
            AssetAction::WAIT => 40,
        }
    }

    fn state_prio(s: AssetState) -> i32 {
        match s {
            AssetState::PULLBACK => 100,
            AssetState::OPTIMAL => 90,
            AssetState::DEFEND => 80,
            AssetState::OVERHEAT => 70,
            AssetState::CRUISE => 60,
            AssetState::CAUTION => 50,
            AssetState::FORMING => 40,
        }
    }

    items.sort_by(|a, b| {
        let ka = (
            if a.action_changed { 1 } else { 0 },
            action_prio(a.action),
            state_prio(a.state),
            a.z_score.unwrap_or(0.0).abs() as i64,
            a.deviation.unwrap_or(0.0).abs() as i64,
        );
        let kb = (
            if b.action_changed { 1 } else { 0 },
            action_prio(b.action),
            state_prio(b.state),
            b.z_score.unwrap_or(0.0).abs() as i64,
            b.deviation.unwrap_or(0.0).abs() as i64,
        );
        kb.cmp(&ka)
    });

    let limit = if state == MarketState::DEFENSIVE { 4 } else { 3 };
    let mut selected = Vec::new();
    let mut seen_actions = std::collections::HashSet::new();

    for asset in items {
        if selected.len() >= limit { break; }
        
        let action_str = format!("{:?}", asset.action);
        // Diversity: prefer different actions, unless action_changed is true
        if asset.action_changed || !seen_actions.contains(&action_str) || selected.is_empty() {
            seen_actions.insert(action_str);
            selected.push(asset);
        }
    }

    selected
}

