"""Deterministic, fail-closed Japanese repository-governance assessment.

This module evaluates evidence that belongs to the repository. It does not
grade a provider model's general Japanese fluency or replace human linguistic
review.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re

# The executable and every argument list are fixed below.
import subprocess  # nosec B404
import sys
from pathlib import Path
from typing import Any

from ai_input_trust import SourceType, assess_input, re_evaluate_high_risk_operation

ROOT = Path(__file__).resolve().parents[1]
ASSESSMENT_WORK_ITEM_ID = "final-japanese-reassessment-replacement-20260731"
ASSESSMENT_WORK_ITEM_ROLE = "final_reassessment"
CORPUS_PATH = ROOT / "tests/fixtures/japanese-capability-corpus.json"
JSON_REPORT_PATH = ROOT / "docs/reference/japanese-capability-assessment.json"
MARKDOWN_REPORT_PATH = ROOT / "docs/reference/japanese-capability-assessment.md"

REQUIRED_JA_DOCS = (
    "README.md",
    "README.zh-CN.md",
    "README.ja.md",
    "docs/trust-layer.md",
    "docs/trust-layer.zh-CN.md",
    "docs/trust-layer.ja.md",
    "docs/getting-started/security-release-verification.md",
    "docs/getting-started/security-release-verification.zh-CN.md",
    "docs/getting-started/security-release-verification.ja.md",
    "docs/reference/documentation-architecture.md",
    "docs/reference/documentation-architecture.ja.md",
    "docs/reference/capability-truth-matrix.json",
    "docs/reference/capability-truth-matrix.md",
    "docs/reference/real-absurd-injection-cases.md",
    "docs/reference/real-absurd-injection-cases.zh-CN.md",
    "docs/reference/real-absurd-injection-cases.ja.md",
    "docs/overview.ja.md",
    "docs/getting-started/installation.ja.md",
    "docs/getting-started/first-work-item.ja.md",
    "docs/reference/how-to-read-cockpit-status.ja.md",
    "docs/reference/repository-workflow.ja.md",
    "docs/reference/work-item-lifecycle-closure.ja.md",
    "docs/reference/troubleshooting.ja.md",
    "docs/reference/upgrade.ja.md",
    "docs/reference/distribution.ja.md",
    "docs/reference/calibration-session.ja.md",
)

# Capability Truth is a required Japanese-facing documentation surface, but its
# JSON and Markdown projections are regenerated by the canonical evidence
# chain. The assessment checks their presence through REQUIRED_JA_DOCS without
# binding their mutable derived bytes into its own source identity.
DERIVED_EVIDENCE_PATHS = frozenset(
    {
        "docs/reference/capability-truth-matrix.json",
        "docs/reference/capability-truth-matrix.md",
    }
)

FINDINGS = {
    "JA-CLI-001": {
        "correctiveWorkItem": "japanese-wizard-cli-corrective-20260729",
        "summary": "Executable Wizard entrypoints do not consume Japanese locale resources.",
    },
    "JA-STATUS-001": {
        "correctiveWorkItem": "japanese-status-output-corrective-20260729",
        "summary": "Cockpit Status has no Japanese derived view or executable parity evidence.",
    },
    "JA-PR-001": {
        "correctiveWorkItem": "japanese-pr-output-corrective-20260729",
        "summary": "Task Outcome PR summary chrome is English-only.",
    },
    "JA-LIFECYCLE-001": {
        "correctiveWorkItem": "japanese-lifecycle-fixture-corrective-20260729",
        "summary": "No executable Japanese adopter fixture covers the governed lifecycle.",
    },
    "JA-DOC-001": {
        "correctiveWorkItem": "japanese-uninstall-documentation-corrective-20260729",
        "summary": "The Japanese engineer path lacks an actionable uninstall procedure.",
    },
    "JA-DOC-FACT-002": {
        "correctiveWorkItem": "japanese-calibration-session-evidence-doc-corrective-20260729",
        "summary": (
            "The Japanese installation guide understates the calibration Session evidence "
            "persisted by record-evidence and can misdirect evidence ownership."
        ),
    },
    "JA-UNINSTALL-RUNTIME-001": {
        "correctiveWorkItem": "installed-detached-uninstaller-runtime-corrective-20260729",
        "summary": (
            "The installed runtime has a proposal/state-output surface but no public uninstall "
            "facts builder, proposal-digest binding, or installed detached removal entrypoint "
            "that performs and verifies filesystem removal."
        ),
    },
}

JAPANESE_UNINSTALL_MARKERS = (
    "<!-- japanese-uninstall: entry -->",
    "<!-- japanese-uninstall: version-neutral -->",
    "<!-- japanese-uninstall: read-only-facts -->",
    "<!-- japanese-uninstall: mode-choice -->",
    "<!-- japanese-uninstall: proposal-runtime-zero-write -->",
    "<!-- japanese-uninstall: preserve-evidence-default -->",
    "<!-- japanese-uninstall: bounded-confirmation -->",
    "<!-- japanese-uninstall: detached-execution -->",
    "<!-- japanese-uninstall: receipt-verification -->",
    "<!-- japanese-uninstall: stop-recovery -->",
    "<!-- japanese-uninstall: purge-separate-confirmation -->",
)


class JapaneseCapabilityError(ValueError):
    """Raised when Japanese assessment evidence cannot be trusted."""


def _digest(value: Any) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


def build_evidence_source(
    paths: list[str] | set[str] | tuple[str, ...], *, root: Path = ROOT
) -> dict[str, Any]:
    """Build a deterministic identity for repository evidence file bytes."""
    root = root.resolve()
    files: list[dict[str, str]] = []
    normalized_paths: set[str] = set()
    for raw_path in paths:
        relative = Path(raw_path)
        if relative.is_absolute():
            raise JapaneseCapabilityError(
                f"Japanese evidence path must be repository-relative: {raw_path}"
            )
        if ".." in relative.parts:
            raise JapaneseCapabilityError(f"Japanese evidence path escapes repository: {raw_path}")
        normalized_paths.add(relative.as_posix())
    for normalized_path in sorted(normalized_paths):
        relative = Path(normalized_path)
        unresolved = root / relative
        path_cursor = unresolved
        while path_cursor != root:
            if path_cursor.is_symlink():
                raise JapaneseCapabilityError(
                    f"Japanese evidence path must not contain a symbolic link: {normalized_path}"
                )
            path_cursor = path_cursor.parent
        candidate = unresolved.resolve()
        try:
            candidate.relative_to(root)
        except ValueError as exc:
            raise JapaneseCapabilityError(
                f"Japanese evidence path escapes repository: {normalized_path}"
            ) from exc
        if not candidate.exists():
            raise JapaneseCapabilityError(f"Japanese evidence file is missing: {normalized_path}")
        if not candidate.is_file():
            raise JapaneseCapabilityError(
                f"Japanese evidence path must be a regular file: {normalized_path}"
            )
        files.append(
            {
                "path": relative.as_posix(),
                "sha256": hashlib.sha256(candidate.read_bytes()).hexdigest(),
            }
        )
    identity: dict[str, Any] = {
        "algorithm": "sha256-canonical-json-v1",
        "fileCount": len(files),
        "files": files,
    }
    identity["digest"] = _digest(identity)
    return identity


def _resolve_git_commit(root: Path, ref: str) -> str:
    try:
        result = subprocess.run(  # nosec B603 B607
            ["git", "-C", str(root), "rev-parse", f"{ref}^{{commit}}"],
            check=True,
            text=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise JapaneseCapabilityError(
            f"Japanese assessment source cannot be resolved: {ref}"
        ) from exc
    commit = result.stdout.strip()
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise JapaneseCapabilityError(
            f"Japanese assessment source did not resolve to a commit: {ref}"
        )
    return commit


def _git_file_sha256(root: Path, commit: str, relative: str) -> str:
    try:
        result = subprocess.run(  # nosec B603 B607
            ["git", "-C", str(root), "show", f"{commit}:{relative}"],
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise JapaneseCapabilityError(
            f"Japanese evidence file cannot be read from expected source: {relative}"
        ) from exc
    return hashlib.sha256(result.stdout).hexdigest()


def validate_expected_source(
    root: Path,
    expected_ref: str,
    *,
    evidence_source: dict[str, Any] | None = None,
) -> str:
    """Require the asserted release source to equal checked-out HEAD."""
    expected = _resolve_git_commit(root, expected_ref)
    head = _resolve_git_commit(root, "HEAD")
    if head != expected:
        raise JapaneseCapabilityError(
            f"Japanese assessment HEAD {head} does not match expected source {expected}"
        )
    if evidence_source is not None:
        files = evidence_source.get("files")
        if not isinstance(files, list):
            raise JapaneseCapabilityError("Japanese evidence source files are missing")
        for entry in files:
            if not isinstance(entry, dict):
                raise JapaneseCapabilityError("Japanese evidence source entry is invalid")
            relative = entry.get("path")
            digest = entry.get("sha256")
            if not isinstance(relative, str) or not isinstance(digest, str):
                raise JapaneseCapabilityError("Japanese evidence source entry is invalid")
            if _git_file_sha256(root, expected, relative) != digest:
                raise JapaneseCapabilityError(
                    f"Japanese evidence file {relative} bytes do not match expected source {expected}"
                )
    return head


def _read(relative: str) -> str:
    path = ROOT / relative
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def _case(
    case_id: str,
    area: str,
    status: str,
    observation: str,
    *,
    source: list[str],
    tests: list[str],
    commands: list[str],
    limitation: str,
    finding_id: str | None = None,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "id": case_id,
        "area": area,
        "status": status,
        "observation": observation,
        "sourceEvidence": source,
        "testEvidence": tests,
        "commandEvidence": commands,
        "limitation": limitation,
    }
    if finding_id is not None:
        value["findingId"] = finding_id
    value["digest"] = _digest(value)
    return value


def _load_corpus() -> dict[str, Any]:
    value = json.loads(CORPUS_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or value.get("corpusVersion") != 1:
        raise ValueError("Japanese capability corpus must use corpusVersion 1")
    entries = value.get("entries")
    if not isinstance(entries, list) or not entries:
        raise ValueError("Japanese capability corpus entries must be a non-empty list")
    return value


def _evaluate_corpus() -> tuple[bool, bool, str]:
    failures: list[str] = []
    stop_failures: list[str] = []
    for entry in _load_corpus()["entries"]:
        if not isinstance(entry, dict):
            failures.append("non-object-entry")
            continue
        try:
            record = assess_input(SourceType(entry["sourceType"]), entry["content"])
        except (KeyError, TypeError, ValueError) as exc:
            failures.append(f"{entry.get('id', 'unknown')}:{exc}")
            continue
        expected_outcomes = entry.get("expectedOutcomes", [])
        if (
            record.instructionAuthority != entry.get("expectedAuthority")
            or record.outcome not in expected_outcomes
        ):
            failures.append(
                f"{entry.get('id')}:authority={record.instructionAuthority},outcome={record.outcome}"
            )
        operation = entry.get("highRiskOperation")
        if operation:
            decision = re_evaluate_high_risk_operation(record, operation)
            if decision.allowed or decision.outcome != "human_confirmation_required":
                stop_failures.append(str(entry.get("id")))
    observation = (
        f"{len(_load_corpus()['entries'])} corpus entries preserved authority and expected outcomes"
        if not failures
        else "corpus mismatches: " + "; ".join(failures)
    )
    return not failures, not stop_failures, observation


def _wizard_is_executable() -> bool:
    entrypoints = (
        ROOT / "scripts/ai_install_wizard.py",
        ROOT / "scripts/ai_calibration_wizard.py",
    )
    executable_tests = (
        (
            ROOT / "tests/test_install_wizard.py",
            "test_japanese_dry_run_uses_executable_locale_resources",
        ),
        (
            ROOT / "tests/test_calibration_wizard.py",
            "test_japanese_render_and_pause_use_executable_locale_resources",
        ),
    )
    return all(
        path.is_file()
        and "ai_wizard_localization" in path.read_text(encoding="utf-8")
        and "--language" in path.read_text(encoding="utf-8")
        for path in entrypoints
    ) and all(
        path.is_file() and test_name in path.read_text(encoding="utf-8")
        for path, test_name in executable_tests
    )


def _status_has_japanese_view() -> bool:
    generator = _read("scripts/ai_generate_status.py")
    checker = _read("scripts/ai_check_status.py")
    makefile = _read("Makefile")
    rendering_tests = _read("tests/test_guards_and_status.py")
    validation_tests = _read("tests/test_core_gates.py")
    return all(
        (
            "--language" in generator,
            ("現在の状態" in generator or "日本語" in generator),
            "--language" in checker,
            "generate-cockpit-status-ja:" in makefile,
            "check-ai-status-ja:" in makefile,
            "test_japanese_status_projection_localizes_chrome_and_preserves_machine_values"
            in rendering_tests,
            "test_status_check_rejects_stale_japanese_projection" in validation_tests,
        )
    )


def _pr_has_japanese_view() -> bool:
    implementation = _read("scripts/ai_render_task_outcome_pr.py")
    makefile = _read("Makefile")
    tests = _read("tests/test_task_outcome_pr_summary.py")
    return all(
        (
            "--language" in implementation,
            ("タスク結果の概要" in implementation or "日本語" in implementation),
            "render-task-outcome-pr:" in makefile,
            "--language" in makefile,
            "test_japanese_pr_summary_localizes_chrome_and_preserves_approved_values" in tests,
            "test_japanese_pr_summary_preserves_sanitization_and_opt_in_boundaries" in tests,
            "test_cli_language_selection_and_unsupported_locale_fail_before_write" in tests,
        )
    )


def _task_outcome_has_japanese_view() -> bool:
    implementation = _read("scripts/ai_render_task_outcome_multilingual.py")
    tests = _read("tests/test_task_outcome_multilingual.py")
    return '"ja": {' in implementation and "## 概要" in tests


def _lifecycle_fixture_exists() -> bool:
    fixture = _read("tests/test_japanese_adopter_lifecycle.py")
    required_tests = (
        "test_japanese_adopter_installs_with_real_wizard_and_release_binding",
        "test_japanese_adopter_calibration_pauses_and_resumes",
        "test_japanese_adopter_recovery_is_confirmation_gated_and_preserves_project",
        "test_japanese_adopter_removal_blocks_unknown_ownership_and_preserves_evidence",
    )
    required_authorities = (
        "run_wizard(",
        '"cockpit-calibrate-session"',
        "plan_rollback(",
        "execute_rollback(",
        "build_proposal(",
        "prepare_detached_removal(",
    )
    return all(f"def {name}(" in fixture for name in required_tests) and all(
        authority in fixture for authority in required_authorities
    )


def _uninstall_path_exists() -> bool:
    installation = _read("docs/getting-started/installation.ja.md")
    troubleshooting = _read("docs/troubleshooting/installation.ja.md")
    uninstall = _read("docs/troubleshooting/uninstall.ja.md")
    troubleshooting_link = (Path("..") / "troubleshooting" / "installation.ja.md").as_posix()
    if uninstall:
        positions = [uninstall.find(marker) for marker in JAPANESE_UNINSTALL_MARKERS]
        return (
            troubleshooting_link in installation
            and "uninstall.ja.md" in troubleshooting
            and "アンインストール" in uninstall
            and all(position >= 0 for position in positions)
            and positions == sorted(positions)
        )
    positions = [installation.find(marker) for marker in JAPANESE_UNINSTALL_MARKERS]
    return (
        "アンインストール" in installation
        and all(position >= 0 for position in positions)
        and positions == sorted(positions)
        and "installation.ja.md#15-ai-cockpit-を無効化またはアンインストールする"
        in _read("docs/reference/upgrade.ja.md")
        and "installation.ja.md#15-ai-cockpit-を無効化またはアンインストールする"
        in _read("docs/reference/troubleshooting.ja.md")
    )


def _calibration_session_evidence_boundary_is_truthful() -> bool:
    installation = _read("docs/reference/calibration-session-model.ja.md")
    return (
        "<!-- calibration-session-evidence-boundary: "
        "combined-stage-seven-column-record,labels-not-actor-proof -->"
        in installation
        and "checklistEvidence" in installation
        and "本人確認" in installation
        and "役割分離" in installation
    )


def _public_uninstall_executor_exists() -> bool:
    makefile = _read("templates/make/Makefile.ai")
    executor = _read("scripts/ai_detached_uninstaller.py")
    catalog = _read("scripts/ai_installer_catalog.json")
    return (
        "ai-cockpit-uninstall-facts:" in makefile
        and "ai-cockpit-uninstall-execute:" in makefile
        and "scripts/ai_detached_uninstaller.py" in makefile
        and '"ai_detached_uninstaller.py"' in catalog
        and "def main(" in executor
        and "proposalDigest" in executor
        and "runtimeRemovalVerified" in executor
    )


def _installed_uninstall_lifecycle_exists() -> bool:
    fixture = _read("tests/test_japanese_adopter_lifecycle.py")
    required = (
        "test_japanese_adopter_executes_installed_uninstall_lifecycle",
        "ai-cockpit-uninstall-facts",
        "ai-cockpit-uninstall-propose",
        "ai-cockpit-uninstall-execute",
        "execute_proposal",
        "Makefile.ai",
    )
    return all(value in fixture for value in required)


def _documents_present() -> tuple[bool, list[str]]:
    missing = [relative for relative in REQUIRED_JA_DOCS if not (ROOT / relative).is_file()]
    return not missing, missing


def _release_gate_is_wired() -> bool:
    makefile = _read("Makefile")
    return (
        "check-japanese-capability:" in makefile
        and "scripts/ai_japanese_capability.py --check" in makefile
        and "scripts/ai_japanese_capability.py --check --require-final-reassessment" in makefile
    )


def evaluate() -> dict[str, Any]:
    corpus_pass, high_risk_pass, corpus_observation = _evaluate_corpus()
    docs_pass, missing_docs = _documents_present()
    japanese_doc_path_pass = docs_pass and _uninstall_path_exists()
    japanese_doc_fact_pass = _calibration_session_evidence_boundary_is_truthful()
    if not japanese_doc_path_pass:
        japanese_doc_finding_id = "JA-DOC-001"
    elif not japanese_doc_fact_pass:
        japanese_doc_finding_id = "JA-DOC-FACT-002"
    else:
        japanese_doc_finding_id = None
    cases = [
        _case(
            "JA-INPUT-001",
            "Japanese register, mixed technical language, encoded input, Unicode, and paths",
            "pass" if corpus_pass else "block",
            corpus_observation,
            source=["tests/fixtures/japanese-capability-corpus.json", "scripts/ai_input_trust.py"],
            tests=["tests/test_japanese_capability.py", "tests/test_input_trust_corpus.py"],
            commands=[
                "PYTHONPATH=scripts .venv/bin/pytest -q tests/test_japanese_capability.py tests/test_input_trust_corpus.py"
            ],
            limitation="Deterministic classification is not general semantic understanding.",
        ),
        _case(
            "JA-HIGH-RISK-001",
            "Japanese high-risk, absurd, Unknown, and human-confirmation STOP boundary",
            "pass" if high_risk_pass else "block",
            "Every corpus high-risk operation requires human_confirmation_required"
            if high_risk_pass
            else "One or more Japanese high-risk entries lost the STOP boundary",
            source=["tests/fixtures/japanese-capability-corpus.json", "scripts/ai_input_trust.py"],
            tests=["tests/test_japanese_capability.py", "tests/test_input_trust.py"],
            commands=[
                "PYTHONPATH=scripts .venv/bin/pytest -q tests/test_japanese_capability.py tests/test_input_trust.py"
            ],
            limitation="The policy boundary does not authenticate the human or execute provider controls.",
        ),
        _case(
            "JA-CLI-001",
            "Executable Wizard and CLI Japanese interaction",
            "pass" if _wizard_is_executable() else "block",
            "Both Wizard entrypoints consume the strict Japanese resource layer with executable tests"
            if _wizard_is_executable()
            else FINDINGS["JA-CLI-001"]["summary"],
            source=[
                "scripts/ai_wizard_localization.py",
                "scripts/ai_install_wizard.py",
                "scripts/ai_calibration_wizard.py",
                "locales/wizard/ja.json",
            ],
            tests=[
                "tests/test_wizard_localization.py",
                "tests/test_install_wizard.py",
                "tests/test_calibration_wizard.py",
            ],
            commands=[
                "PYTHONPATH=scripts .venv/bin/pytest -q tests/test_wizard_localization.py tests/test_install_wizard.py tests/test_calibration_wizard.py"
            ],
            limitation="Resource parity alone cannot prove executable Japanese interaction.",
            finding_id=None if _wizard_is_executable() else "JA-CLI-001",
        ),
        _case(
            "JA-STATUS-001",
            "Cockpit Status Japanese parity",
            "pass" if _status_has_japanese_view() else "block",
            "Japanese Status view is derived from the same machine facts"
            if _status_has_japanese_view()
            else FINDINGS["JA-STATUS-001"]["summary"],
            source=[
                "scripts/ai_generate_status.py",
                "scripts/ai_check_status.py",
                "Makefile",
            ],
            tests=["tests/test_guards_and_status.py", "tests/test_core_gates.py"],
            commands=[
                "make generate-cockpit-status-ja CONTRACT=<contract> SUMMARY=<summary>",
                "make check-ai-status-ja CONTRACT=<contract> SUMMARY=<summary>",
            ],
            limitation="A Japanese guide to an English Status is not output parity.",
            finding_id=None if _status_has_japanese_view() else "JA-STATUS-001",
        ),
        _case(
            "JA-PR-001",
            "Task Outcome PR summary Japanese parity",
            "pass" if _pr_has_japanese_view() else "block",
            "Japanese PR chrome preserves the approved field set"
            if _pr_has_japanese_view()
            else FINDINGS["JA-PR-001"]["summary"],
            source=["scripts/ai_render_task_outcome_pr.py", "Makefile"],
            tests=["tests/test_task_outcome_pr_summary.py"],
            commands=[
                "PYTHONPATH=scripts:. .venv/bin/pytest -q tests/test_task_outcome_pr_summary.py",
                "make render-task-outcome-pr OUTCOME=<outcome> PROFILE=<profile> LANGUAGE=ja",
            ],
            limitation="PR localization must not translate or invent arbitrary evidence prose.",
            finding_id=None if _pr_has_japanese_view() else "JA-PR-001",
        ),
        _case(
            "JA-TASK-OUTCOME-001",
            "Task Outcome Japanese derived view",
            "pass" if _task_outcome_has_japanese_view() else "block",
            "Japanese Task Outcome chrome is derived from unchanged machine facts"
            if _task_outcome_has_japanese_view()
            else "Japanese Task Outcome parity evidence is missing",
            source=["scripts/ai_render_task_outcome_multilingual.py"],
            tests=["tests/test_task_outcome_multilingual.py"],
            commands=["PYTHONPATH=. .venv/bin/pytest -q tests/test_task_outcome_multilingual.py"],
            limitation="Arbitrary evidence prose remains source text and is not machine-translated.",
        ),
        _case(
            "JA-LIFECYCLE-001",
            "Executable Japanese adopter lifecycle through installed uninstall execution",
            "pass" if _lifecycle_fixture_exists() else "block",
            "Isolated Japanese adopter fixture executes installation, calibration, recovery, "
            "uninstall facts, digest-bound proposal, detached removal, and receipt verification"
            if _lifecycle_fixture_exists()
            else FINDINGS["JA-LIFECYCLE-001"]["summary"],
            source=[
                "docs/getting-started/installation.ja.md",
                "scripts/ai_calibrate.py",
                "scripts/ai_rollback.py",
                "scripts/ai_uninstall_proposal.py",
                "scripts/ai_detached_uninstaller.py",
            ],
            tests=["tests/test_japanese_adopter_lifecycle.py"],
            commands=["PYTHONPATH=. .venv/bin/pytest -q tests/test_japanese_adopter_lifecycle.py"],
            limitation=(
                "The fixture proves bounded preserve-evidence filesystem removal and Japanese "
                "evidence handling; it does not prove purge, general fluency, provider "
                "operations, or real adopter platform quality."
            ),
            finding_id=None if _lifecycle_fixture_exists() else "JA-LIFECYCLE-001",
        ),
        _case(
            "JA-DOC-001",
            "Japanese installation, calibration, upgrade, rollback, uninstall, and recovery path",
            "pass" if japanese_doc_path_pass and japanese_doc_fact_pass else "block",
            "Required Japanese documents, the uninstall path, and calibration evidence ownership are current"
            if japanese_doc_path_pass and japanese_doc_fact_pass
            else (
                FINDINGS["JA-DOC-001"]["summary"]
                + (f"; missing documents: {', '.join(missing_docs)}" if missing_docs else "")
                if not japanese_doc_path_pass
                else FINDINGS["JA-DOC-FACT-002"]["summary"]
            ),
            source=list(REQUIRED_JA_DOCS),
            tests=["tests/test_docs_metadata.py", "tests/test_japanese_capability.py"],
            commands=["make check-docs-metadata"],
            limitation="Structure and terminology checks do not replace native technical editing.",
            finding_id=japanese_doc_finding_id,
        ),
        _case(
            "JA-UNINSTALL-RUNTIME-001",
            "Installed public detached uninstall execution",
            "pass"
            if _public_uninstall_executor_exists() and _installed_uninstall_lifecycle_exists()
            else "block",
            "The installed repository exposes a public detached removal entrypoint and a clean-adopter lifecycle test"
            if _public_uninstall_executor_exists() and _installed_uninstall_lifecycle_exists()
            else FINDINGS["JA-UNINSTALL-RUNTIME-001"]["summary"],
            source=[
                "templates/make/Makefile.ai",
                "scripts/ai_uninstall_facts.py",
                "scripts/ai_uninstall_proposal.py",
                "scripts/ai_detached_uninstaller.py",
                "scripts/ai_installer_catalog.json",
                "docs/reference/installed-lifecycle.md",
            ],
            tests=[
                "tests/test_japanese_capability.py",
                "tests/test_japanese_adopter_lifecycle.py",
            ],
            commands=[
                "PYTHONPATH=scripts .venv/bin/pytest -q tests/test_japanese_capability.py tests/test_japanese_adopter_lifecycle.py"
            ],
            limitation=(
                "The installed executor is limited to preserve-evidence Runtime-file removal; "
                "purge, provider permissions, and platform locks remain outside this evidence."
            ),
            finding_id=(
                None
                if _public_uninstall_executor_exists() and _installed_uninstall_lifecycle_exists()
                else "JA-UNINSTALL-RUNTIME-001"
            ),
        ),
        _case(
            "JA-DOC-STRUCTURE-001",
            "Japanese document metadata and three-language structure",
            "pass" if docs_pass else "block",
            "Required Japanese engineer entry documents exist and remain under metadata checks"
            if docs_pass
            else f"missing documents: {', '.join(missing_docs)}",
            source=list(REQUIRED_JA_DOCS),
            tests=["tests/test_docs_metadata.py", "tests/test_trust_layer_docs.py"],
            commands=["make check-docs-metadata", "make check-trust-layer-docs"],
            limitation="Automated parity checks cannot establish complete translation quality.",
        ),
        _case(
            "JA-RELEASE-GATE-001",
            "Mandatory pre-release Japanese evidence gate",
            "pass" if _release_gate_is_wired() else "block",
            "check-release-preflight requires the current Japanese assessment"
            if _release_gate_is_wired()
            else "release preflight does not invoke the Japanese assessment",
            source=["Makefile", "scripts/ai_japanese_capability.py"],
            tests=["tests/test_makefile.py", "tests/test_japanese_capability.py"],
            commands=["make check-japanese-capability", "make check-release-preflight"],
            limitation="Passing the gate proves only the in-repository matrix at the assessed source.",
        ),
        _case(
            "JA-GENERAL-FLUENCY",
            "General Japanese model fluency and human translation quality",
            "limitation",
            "No provider-backed or native-human-reviewed general fluency evidence is claimed.",
            source=[],
            tests=[],
            commands=[],
            limitation="General Japanese provider/model fluency and human translation quality remain unproved.",
        ),
    ]
    blocking_findings = []
    for case in cases:
        finding_id = case.get("findingId")
        if case["status"] == "block" and isinstance(finding_id, str):
            blocking_findings.append(
                {
                    "id": finding_id,
                    "caseId": case["id"],
                    **FINDINGS[finding_id],
                }
            )
    evidence_paths = {
        path
        for case in cases
        for field in ("sourceEvidence", "testEvidence")
        for path in case[field]
        if path not in DERIVED_EVIDENCE_PATHS
    }
    evidence_paths.add("scripts/ai_japanese_capability.py")
    result: dict[str, Any] = {
        "assessmentVersion": 3,
        "workItemId": ASSESSMENT_WORK_ITEM_ID,
        "workItemRole": ASSESSMENT_WORK_ITEM_ROLE,
        "scope": "bounded repository-governance Japanese handling",
        "evidenceSource": build_evidence_source(evidence_paths),
        "corpus": {
            "path": str(CORPUS_PATH.relative_to(ROOT)),
            "digest": _digest(_load_corpus()),
            "entryCount": len(_load_corpus()["entries"]),
        },
        "cases": cases,
        "blockingFindings": blocking_findings,
        "limitations": [
            "This assessment does not claim general model fluency, translation quality, or provider behavior.",
            "Every English-inferred, missing, stale, or non-executable Japanese capability is release-blocking.",
        ],
    }
    result["digest"] = _digest(result)
    return result


def render_json(result: dict[str, Any]) -> str:
    return json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_markdown(result: dict[str, Any]) -> str:
    lines = [
        "---",
        "author: Ray",
        'title: "Japanese Capability Assessment"',
        "description: Comprehensive, bounded, evidence-backed Japanese repository-governance release gate.",
        "---",
        "",
        "# Japanese Capability Assessment",
        "",
        "> This is a release gate, not a claim of general Japanese model fluency.",
        "",
        f"- Assessment Work Item: `{result['workItemId']}`",
        f"- Work Item role: `{result['workItemRole']}`",
        f"- Assessment digest: `{result['digest']}`",
        (
            f"- Evidence source: `{result['evidenceSource']['digest']}` "
            f"({result['evidenceSource']['fileCount']} files; "
            f"`{result['evidenceSource']['algorithm']}`)"
        ),
        f"- Corpus: `{result['corpus']['path']}` (`{result['corpus']['entryCount']}` entries)",
        f"- Blocking findings: `{len(result['blockingFindings'])}`",
        "- [Machine-readable assessment](japanese-capability-assessment.json)",
        "",
        "## Evidence boundary",
        "",
        "The matrix evaluates current repository behavior, executable evidence, and Japanese engineer paths. Capability Truth remains a required report surface, but its regenerated projections are deliberately excluded from this assessment's bound source identity so the canonical generator chain stays acyclic. Missing or English-inferred evidence is blocking. General provider/model fluency and native-human translation review remain explicit non-claims.",
        "",
        "## Matrix",
        "",
        "| ID | Area | Status | Observation | Source / tests / commands |",
        "| --- | --- | --- | --- | --- |",
    ]
    for case in result["cases"]:
        evidence = [
            *(f"`{item}`" for item in case["sourceEvidence"]),
            *(f"`{item}`" for item in case["testEvidence"]),
            *(f"`{item}`" for item in case["commandEvidence"]),
        ]
        observation = case["observation"].replace("|", "\\|")
        lines.append(
            f"| `{case['id']}` | {case['area']} | **{case['status']}** | "
            f"{observation} | {'; '.join(evidence) or 'none'} |"
        )
    lines.extend(["", "## Blocking findings", ""])
    if result["blockingFindings"]:
        for finding in result["blockingFindings"]:
            lines.append(
                f"- `{finding['id']}`: {finding['summary']} Corrective Work Item: "
                f"`{finding['correctiveWorkItem']}`."
            )
    else:
        lines.append("- None within the declared repository-governance scope.")
    lines.extend(
        [
            "",
            "Each blocker requires its own Contract, implementation, verification, PR, Hosted CI, merge, `make ai-close-work-item`, branch cleanup, and a fresh assessment. A blocker cannot be cleared by editing this report.",
            "",
            "## Reproduce",
            "",
            "```bash",
            "PYTHONPATH=scripts .venv/bin/python scripts/ai_japanese_capability.py --check",
            "```",
            "",
            "## Limitations",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in result["limitations"])
    return "\n".join(lines) + "\n"


def report_drift(result: dict[str, Any], *, json_path: Path, markdown_path: Path) -> list[str]:
    errors: list[str] = []
    expected_json = render_json(result)
    expected_markdown = render_markdown(result)
    if not json_path.is_file() or json_path.read_text(encoding="utf-8") != expected_json:
        errors.append(f"stale Japanese assessment JSON: {json_path}")
    if (
        not markdown_path.is_file()
        or markdown_path.read_text(encoding="utf-8") != expected_markdown
    ):
        errors.append(f"stale Japanese assessment Markdown: {markdown_path}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write JSON and Markdown reports")
    mode.add_argument("--check", action="store_true", help="verify checked-in reports")
    parser.add_argument(
        "--source-commit",
        help="require the asserted source commit to equal checked-out HEAD",
    )
    parser.add_argument(
        "--require-final-reassessment",
        action="store_true",
        help="require the checked report to be an independent final reassessment",
    )
    args = parser.parse_args()
    try:
        source_commit = args.source_commit
        if source_commit is None:
            source_commit = os.environ.get("RELEASE_PREFLIGHT_SOURCE_COMMIT") or None
        if source_commit is not None and not source_commit.strip():
            raise JapaneseCapabilityError("Japanese assessment source commit must not be empty")
        result = evaluate()
        if source_commit is not None:
            validate_expected_source(
                ROOT,
                source_commit,
                evidence_source=result["evidenceSource"],
            )
    except JapaneseCapabilityError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    if args.write:
        JSON_REPORT_PATH.write_text(render_json(result), encoding="utf-8")
        MARKDOWN_REPORT_PATH.write_text(render_markdown(result), encoding="utf-8")
    if args.require_final_reassessment and result.get("workItemRole") != "final_reassessment":
        print(
            "release requires workItemRole=final_reassessment; "
            f"found {result.get('workItemRole', 'missing')}",
            file=sys.stderr,
        )
        return 2
    if args.check:
        errors = report_drift(
            result, json_path=JSON_REPORT_PATH, markdown_path=MARKDOWN_REPORT_PATH
        )
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 2
    print(render_json(result), end="")
    if result["blockingFindings"]:
        print(
            "Japanese capability assessment is release-blocking: "
            + ", ".join(finding["id"] for finding in result["blockingFindings"]),
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
